### PR TITLE
(Try to) refactor most of the script...

### PR DESCRIPTION
**Pull request by reo101**
`s/sh/bash` - the script uses the bash-specific `[[ expr ]]` syntax
Enclose all variable references in quotes and braces
Swap out the `if` chains with `case` statements
Make `$PROMPT` and `$VIDEO_PLAYER` available for setting from the environment
Rename directory variables' names
Sanitize all comments (space after the `#`)
Sanitize all function declarations (spaces around name, parenthesis and braces)
Use here-documents for big multilined prints
Parametrize cache location - now dictated by the XDG standards
Replace tabs with spaces

### CODE REVIEW

**Comment by SamIsTheFBI** [comment]
Hi there!

I'm sorry for the late response. I just saw your commit, tried it on my machine and found some problems.

First, there is no notification for when the script is already running (in line 7 there is ! in your commit).
I can't seem to get to the prompt unless I make a dummy watchmenu-last-played file in the watchmenu cache directory. And when I do make a dummy last-played file, I can't play it.
And a lot of errors in navigation, when trying to open a video file (Movies & Videos menu) and when trying to choose a season in "Seasons Menu" of a TV show.

I don't know If it worked properly on your device but on my device it's not.

**Comment by reo101** [comment]
Thank you for the feedback, I will look into the issues :D

**Comment by SamIsTheFBI** [comment]
Hey, just wanted to let you know that I changed a few things so you might wanna make necessary changes to your script.   

image
image
image

**Comment by reo101** [comment]
Great idea to use bash arrays! I've almost forgotten they exist 😄. I think I've managed to rebase the refactor on top of your new changes. Ping me again if something's acting up 😄

**Comment by SamIsTheFBI** [comment]
You had messed up the code to update videos list but it's fixed now. Also I found that using a different variable for main menu selection fixes the navigation issue as shown in the video. 

https://user-images.githubusercontent.com/70562711/180630522-e3c75d1c-3c29-4fa1-899b-5418dd1997cf.mp4

I changed the variable PROMPT to WATCHMENU_PROMPT to avoid any possible conflicts. Not using %s in those printf statements so Japanese and other characters would show up. And lastly, using sort -V only in seasons directory because of this:

image

**Comment by reo101** [comment]
Thank you for the merge 😄. I've seen that `sort -V` floating around a few times but noticed that you removed it from many places somewhere in your latest commits and that's why I thought you're getting rid of it. I will definitely read up about the `%s` problem in `printf` (I've heard that `%b` might be of help).

**Pull request merged**
